# Generated by Django 5.0.4 on 2024-04-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=100)),
                ('img_content', models.CharField(max_length=100)),
            ],
        ),
    ]
